### ISSUE TITLE
License type missing

### ISSUE THREAD

**Issue by AlanVerbner** [PearlVentures/Essence#10]
Hello, how are you?

Sometimes we cannot use some libs in our projects because the license type. I wasn't able to find it in the repo.

Thanks! :smile:

**Comment by hetmann** [comment]
Hello AlanVerbner,

We are working daily at Essence framework.Thank you for the feedback.
We just pushed the missing License / License-docs files. Hope the license type is OK for you to build your apps?! :)

Thanks!

**Comment by AlanVerbner** [comment]
Awesome! Thanks! I will try it now, heheheh

 :+1:
