### ISSUE TITLE
Is this available as npm or bower module?

### ISSUE THREAD

**Issue by vasya10** [PearlVentures/Essence#11]
This is a great framework and well implemented as React components! Would love to try it out. 

A couple of questions:

1. Will this be available via npm or bower module?
2. What is the licensing model ?

**Comment by chinciusan** [comment]
Hi vasya10!
Essence will be available soon as an npm package. (that is a couple of days) 
About the licensing model, it was updated.

**Comment by vasya10** [comment]
Thanks for the quick response!

**Comment by hetmann** [comment]
Hi @vasya10 ,

Just published the NPM Package for React-Essence, so here you go:

Install: 
```jsx
npm install react-essence@latest --save
```

Usage: 
- Import / Require
```javascript
import { Btn, BtnItem, Icon, Block, Text } from 'react-essence';
```

- React-Essence components example
```jsx
<Block type='div' classes={'brick brick-6'}>

	<Text type='h2' classes={"e-display-1 e-text-blue-700"}>Some title</Text>
	<Block type='div' classes={'e-text-grey-400 e-caption'}>
		<Text>Some text</Text>
	</Block>

	<Block type='div' classes={'brick brick-6 e-text-right e-padding-top-15'}>
		<BtnItem
			classes={'raised e-background-pink-A200'}
			onClick={this.yourActionOnClick}
			label='Button 1'/>

		<BtnItem
			classes={'raised e-background-pink-A200'}
			onClick={this.yourActionOnClick}
			label='Button 2'/>
	</Block>
</Block>
```
