### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by hipertracker** [PearlVentures/Essence#13]
Do you plan to release a npm package? It's not clear how to use that library in the React project which does not resemble what's inside the "project-template" folder. The code inside is not the best way to use React. JSX should not be used that way. It's too slow and not flexible, because it is not modular (I use jspm.io which uses ES6 modules and works smoothly with NPM and Bower packages).

The good example of exposing React components https://github.com/jessy1092/react-semantify/blob/develop/src/index.js

Why you return React as a part of Essence components??https://github.com/PearlVentures/Essence/blob/master/src/js/components.js#L4

**Comment by hetmann** [comment]
Hi @hipertracker,

We included React framework in Essence in order to build a bundle without the need to include external React. So for now React is part of Essence as a component.

In the next couple of days we will create NPM and Bower packages so anyone can build their own bundles.

Thank you for your feedback.

**Comment by hartmamt** [comment]
For now I've been doing this as a work around:

`npm i PearlVentures/Essence --save`

And then including it in my project like this:

```javascript

import Essence from 'essence/src/js/components.js';
var Btn = Essence.Btn;
```

I also add just downloaded essence.css and icons.css and referenced them in my HTML...I haven't messed with less yet.  BTW I use webpack in this project and the only issue I had was making sure to change all my React imports from

`import React from 'react';`

to

`import React from 'react/addons';`

**Comment by hipertracker** [comment]
I found  [react-essence](https://www.npmjs.com/package/react-essence) Npm package, but unfortunately it uses JSX inside which is not recognised by JavaScript. I use Webpack with babel-loader and it works with ES6 modules and JSX syntax. But when I run ```import Components from 'react-essence'``` I got a massive list of errors. All related to not recognised JSX format. I guess, it's because the package is not ES5 compatible.

**Comment by hartmamt** [comment]
Here is a webpack starter project that uses Essence.  I had to fork the repo because the package.son required React, and webpack was including it twice.  Instead of the nom module, I used NPM to then point to my forked repo.  Hopefully the react-essence nom module will be available soon.  Here is my starter project if you want take a look. https://github.com/University-Of-Cincinnati/essence-webpack

**Comment by hipertracker** [comment]
Looks great, buy why the starter is using Bootstrap? Is it needed? Is it not a risk to mix css  between Essence and Bootstrap? Can I safely replace Bootstrap with Semantic-UI?

**Comment by hartmamt** [comment]
Yeah. I just had it in because the grid system is more familiar to me.  I'll remove bootstrap from the example so it isn't confusing though.

**Comment by FoxxMD** [comment]
@hetmann any update?

**Comment by hipertracker** [comment]
My suggestion: have a look at  [react-bootstrap](https://www.npmjs.com/package/react-bootstrap) package, please. It keeps all source files in consistent ES6+JSX format. The NPM files are transpiled by Webpack and babel-node into universal UMD. The package is clean, modular and works fine for Node and the browsers.

**Comment by hetmann** [comment]
Guys,

Just published the NPM Package for React-Essence, so here you go:

Install: 
```jsx
npm install react-essence@latest --save
```

Usage: 
- Import / Require
```javascript
import { Btn, BtnItem, Icon, Block, Text } from 'react-essence';
```

- React-Essence components example
```jsx
<Block type='div' classes={'brick brick-6'}>

	<Text type='h2' classes={"e-display-1 e-text-blue-700"}>Some title</Text>
	<Block type='div' classes={'e-text-grey-400 e-caption'}>
		<Text>Some text</Text>
	</Block>

	<Block type='div' classes={'brick brick-6 e-text-right e-padding-top-15'}>
		<BtnItem
			classes={'raised e-background-pink-A200'}
			onClick={this.yourActionOnClick}
			label='Button 1'/>

		<BtnItem
			classes={'raised e-background-pink-A200'}
			onClick={this.yourActionOnClick}
			label='Button 2'/>
	</Block>
</Block>
```

**Comment by FoxxMD** [comment]
:+1: awesome thank you
