### ISSUE TITLE
Compare/Contrast to Material-UI

### ISSUE THREAD

**Issue by newtack** [PearlVentures/Essence#14]
I like the look and feel of your library.

Can you compare/contrast Essence to material-ui? They seem to be trying to achieve similar aims.

One of the things that the material-ui project is moving to in 0.8 is inline CSS in the components (see https://github.com/callemall/material-ui/blob/2eb14e69c411e9165d696df1a88d4ac8036591bf/CHANGELOG.md for more details), which I would like to see in this library as well.

**Comment by hetmann** [comment]
The idea is the same but we build Essence for our projects. We use inline CSS in the Essence Native project, but there we created our Styles object for each component (that took us a lot of work).

We like the inline style idea and we will update all the components to use a classic html "style" options.

Maybe in the future we can create a hybrid JS CSS with CSS.
