### ISSUE TITLE
Tabs not working as they should

### ISSUE THREAD

**Issue by raulmatei** [PearlVentures/Essence#17]
**How to reproduce:**

1. Open up the tabs component's example
2. Identify the active tab (it should be the first one)
3. You can identify it as active because the text stands out a little bit more than the others
4. Click on another tab - the content changes and suddenly a yellow border appears at the bottom of the tab
5. Now click on one of the other tabs (you choose) - the content changes and the yellow border smoothly changes its position to the active tab

**What's the expected result:**
 - active tab should always have a bottom border if the tabs are built that way
 - the bottom border should always be moved smoothly, with the nice animation that already exists, to the next clicked tab

**What's the actual result:**
As stayed above:
  - the active tab doesn't have the bottom border
  - the border appears only when you click on to another tab
  - there's no animation on the initial border appearence

**Comment by hetmann** [comment]
Tabs: added new method renderFirstItem() on componentDidMount (file: TabMenu.js)
