### ISSUE TITLE
fresh install and nothing

### ISSUE THREAD

**Issue by SOSANA** [PearlVentures/Essence#19]
Am I missing something? 

```
Git clone https://github.com/PearlVentures/Essence.git
npm install
grunt
```
I obviously go to my localhost page and nothing :(

In cli grunt is waiting
![image](https://cloud.githubusercontent.com/assets/2634185/7997877/5e4fab32-0af1-11e5-8212-303f8f5f3df9.png)

**Comment by hetmann** [comment]
Hello @SOSANA ,
You can simply edit and save any LESS or JS fle and it will start compiling.

**Comment by SOSANA** [comment]
Oh, So I need to do this before I can render the view on my local server? Shouldn't it just render by default?

**Comment by hetmann** [comment]
When initiated the grunt watch package doesn't know what files are modified only after you save/modify the content,after that will start compiling. 

My suggestion:
- in tasks/watch.js add "**atBegin: true**" to watch options as shown below:
```
options: {
  interrupt: true,
  atBegin: true
}
```
