### ISSUE TITLE
ClassNames util is modifying state in components directly

### ISSUE THREAD

**Issue by Ganonside** [PearlVentures/Essence#21]
when `Utils.classNames(self.state.classes, self.props.classes)` is called, the reference to `self.state.classes` is being passed in and modified. This causes a bug where you cannot remove extra classes from a component after you have set it.

**Comment by Ganonside** [comment]
#22 this is my fix to the problem

**Comment by hetmann** [comment]
Thanks @Ganonside pull request has been completed.
