### ISSUE TITLE
Navigation lists don't play nice with React components

### ISSUE THREAD

**Issue by Ganonside** [PearlVentures/Essence#25]
when you try to create a `Navigation` bar with submenus dynamically using `React` components, something within the `ListItem` component breaks.

```js
var navMenus: [
  {
    label: 'Menu1', subItems: [{ text: 'itemText' }, {...}, {...}]
  }, {
    label: 'Menu2', subItems: [{ text: 'itemText' }, {...}, {...}]
  }, {
    ...
  }, {
    label: 'MenuN', subItems: [{ text: 'itemText' }, {...}, {...}]
  }
];
```

Given an object with a structure similar to the above, this works:
```
let mapSubItems = (subItem) => {
  return (
    <Block type='li'>
      <Text>{subItem.text}</Text>
    </Block>
  );
};

let mapListItems = (listItem) => {
  let items = listItem.subItems.map(mapSubItems);

  let text = listItem.label;
  let link = `#${text.toLowerCase()}`;

  return (
    <ListItem contentLink={link} contentText={text} hasSubmenu={true} listType='navigation'>
      {items}
    </ListItem>
  );
};

var NavBar = React.createClass({
  render() {
    let listItems = navMenus.map(mapListItems);

    return (
      <Navigation header='Nav' live={false} logo='assets/img/essence_icon.png'>
        <List classes='e-list-navigation' id='Nav'>
          {listItems}
        </List>
      </Navigation>
    );
  }
});
```

But this code doesn't:
```
let NavSubItem = React.createClass({
  render() {
    return (
      <Block type='li'>
        <Text>{this.props.text}</Text>
      </Block>
    );
  }
});

let NavListItem = React.createClass({
  render() {
    let subItems = this.props.subItems.map((subItem) => <NavSubItem text={subItem.text} />);
    
    let text = this.props.text;
    let link = `#${text.toLowerCase()}`;
    
    return (
      <ListItem contentLink={link} contentText={text} hasSubmenu={true} listType='navigation'>
        {subItems}
      </ListItem>
    );
  }
});

let NavBar = React.createClass({
  render() {
    let listItems = navMenus.map((menu) => <NavListItem label={menu.label} subItems={menu.subItems} />);
    
    return (
      <Navigation header='Nav Bar' live={false} logo='assets/img/essence_icon.png'>
        <List classes='e-list-navigation' id='NavBar'>
          {listItems}
        </List>
      </Navigation>
    );
  }
});
```
 
I think it has something to so with the `id` of the `ListItem`s being generated. When you use `React` components the `id` doesn't automatically get set, unlike when you don't use `React` components, for some reason which I believe is confusing the event handler that tells the component to hide or show the submenu.

**Comment by hetmann** [comment]
The ```<Navigation />``` component is wrapping the ```<List />``` and ```<ListItem />``` components inside an ```<aside>``` html tag. 

The example from Essence Components is build with ```<List />``` and ```<ListItem />``` but you can use the ```<Text />``` and ```<Block />``` components to build your own list view, so for a dynamic ```<Navigation />``` menu my suggestion is to build a custom List.

**Comment by hetmann** [comment]
For this issue I added the ID attribute on the ```ListItem``` component for navigation type, **ID** is auto generated. 

For other issues for ```Navigation``` / ```ListItem``` component please use the branch **navigation-issue-25**
