### ISSUE TITLE
Tabs headers are unreachable if not enough width

### ISSUE THREAD

**Issue by nMustaki** [PearlVentures/Essence#26]
Hi,
First thanks for the project !

Steps to reproduce:
- go to the tabs example page on a mobile device
- the third tab header is invisible

Maybe add a horizontal scroll or a select ?

**Comment by hartmamt** [comment]
We have this same issue.  Would be nice if tabs could scroll or non visible tabs moved to a 'more' dropdown.

**Comment by hetmann** [comment]
Tabs component is fixed, I'd added a method to render Highlighter css values on resize & scroll & touch.
That should do the trick. Let me know if you find other issues.
