### ISSUE TITLE
AppBar doesn't read classes property.

### ISSUE THREAD

**Issue by RakanNimer** [PearlVentures/Essence#27]
Adding classes to AppBar Component doesn't do anything.
Example code :  
```jsx
<AppBar classes={'e-background-indigo-400 e-text-white'} >
</AppBar>
```
In src/js/components/AppBar.js in the _render_ function the classes are not added. 

Is this by design ? 

Cheers !

**Comment by hetmann** [comment]
Hello @RakanNimer yes is intented to render without extra classes but soon we will include this option.

**Comment by hetmann** [comment]
@RakanNimer I added the class support for AppBar component using props.classes

**Comment by RakanNimer** [comment]
Awesome! Thanks :)
Great work on the framework!
