### ISSUE TITLE
NPM release doesn't have rebuilt distribution files.

### ISSUE THREAD

**Issue by hartmamt** [PearlVentures/Essence#31]
Is it possible to run gulp distribution before publishing the module to npm?  Just asking because I have a few PRs in the 0.0.21 release, but I can't use them unless I build the module from source.  Let me know if I am doing something wrong or if I can help in anyway!  Thanks so much for this library.

**Comment by hetmann** [comment]
Sorry for the delay we were working at essence jQuery plugins.
