### ISSUE TITLE
Menu component has web accessibility issues

### ISSUE THREAD

**Issue by AliciaWamsley** [PearlVentures/Essence#34]
An element's ID must be unique in the DOM. The Menu id is the same as the child ul and div ids. This is not disability compliant - https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_02

**Comment by hartmamt** [comment]
Thanks for merging this.  Maintainers, can you publish a new release to NPM containing this PR?

**Comment by raulmatei** [comment]
I'll close this one, thanks for this PR, we've also updated the NPM package.
