### ISSUE TITLE
Stacked components - click outside

### ISSUE THREAD

**Issue by fibric** [PearlVentures/Essence#6]
Component examples on essense.pearlhq.com have all together a problem when stacked components like menus or popups are shown. They do not disappear when clicking outside of components ui.
Here on AppBar I can open both sub menus at same time. Just because first menu does not listen to outside click.
![screenshot 2015-04-05 02 32 19](https://cloud.githubusercontent.com/assets/623932/6995242/09215672-db3c-11e4-9f99-eb2e355af035.png)

DatePicker has the same issue, it pops up and does not disappear when clicking far outside of datepicker ui. Same applies to Menus.

Strange here is, the Dialog does disappear on click outside.

**Comment by mpatachi** [comment]
Thank you Danny for spotting this out. We'll take a look in the next couple of days and come back with a resolution.

**Comment by fibric** [comment]
Welcome. Same applies to Firefox and Safari. Seems it isn't a Chrome-only bug.

**Comment by lorandm** [comment]
Great find Danny, many thanks for this. We'll get right to it!

**Comment by hetmann** [comment]
Done. Thanks Danny.
