### ISSUE TITLE
full Dialog bug

### ISSUE THREAD

**Issue by emil-perhinschi** [PearlVentures/Essence#8]
go to Components List -> Dialogs -> Show Full Dialog: the window is shaded and the modal is displayed; click on the icon with class e-icon-action-settings-bluetooth to the left of the "New event" string: the modal disappears but the window stays shaded 

browser: Firefox 37.0.2 on Linux Mint 17.1 Rebecca

**Comment by hetmann** [comment]
When clicked on the "e-icon-action-settings-bluetooth" it will scroll to the top of the page (see the href link of the component). This is an example and that component can be changed to a simple icon component without the "href".

P.S.: click on the icon "e-icon-action-settings-bluetooth", then scroll down until you see the "Full Dialog". To resolve the issue please add a styling css: ```position: fixed;```
